apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysqlcred-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: data/mysqlcred
        property: username
    - secretKey: password
      remoteRef:
        key: data/mysqlcred
        property: password
